import { CarryDifficultyCreationModel } from '@dungeon-hub/api-client';

/**
 * Type-safe mapping of ingame carry types to display labels.
 * TypeScript will error if the enum changes and this mapping is not updated.
 */
export const INGAME_CARRY_TYPE_LABELS: Record<CarryDifficultyCreationModel.IngameCarryTypeEnum, string> = {
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor1Completion]: 'Floor 1 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor1S]: 'Floor 1 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor1SPlus]: 'Floor 1 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor1]: 'Floor 1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor2Completion]: 'Floor 2 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor2S]: 'Floor 2 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor2SPlus]: 'Floor 2 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor2]: 'Floor 2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor3Completion]: 'Floor 3 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor3S]: 'Floor 3 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor3SPlus]: 'Floor 3 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor3]: 'Floor 3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor4Completion]: 'Floor 4 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor4S]: 'Floor 4 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor4SPlus]: 'Floor 4 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor4]: 'Floor 4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor5Completion]: 'Floor 5 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor5S]: 'Floor 5 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor5SPlus]: 'Floor 5 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor5]: 'Floor 5',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor6Completion]: 'Floor 6 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor6S]: 'Floor 6 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor6SPlus]: 'Floor 6 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor6]: 'Floor 6',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor7Completion]: 'Floor 7 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor7S]: 'Floor 7 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor7SPlus]: 'Floor 7 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Floor7]: 'Floor 7',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode1Completion]: 'Master Mode 1 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode1S]: 'Master Mode 1 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode1SPlus]: 'Master Mode 1 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode1]: 'Master Mode 1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode2Completion]: 'Master Mode 2 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode2S]: 'Master Mode 2 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode2SPlus]: 'Master Mode 2 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode2]: 'Master Mode 2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode3Completion]: 'Master Mode 3 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode3S]: 'Master Mode 3 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode3SPlus]: 'Master Mode 3 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode3]: 'Master Mode 3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode4Completion]: 'Master Mode 4 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode4S]: 'Master Mode 4 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode4SPlus]: 'Master Mode 4 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode4]: 'Master Mode 4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode5Completion]: 'Master Mode 5 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode5S]: 'Master Mode 5 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode5SPlus]: 'Master Mode 5 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode5]: 'Master Mode 5',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode6Completion]: 'Master Mode 6 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode6S]: 'Master Mode 6 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode6SPlus]: 'Master Mode 6 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode6]: 'Master Mode 6',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode7Completion]: 'Master Mode 7 Completion',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode7S]: 'Master Mode 7 S',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode7SPlus]: 'Master Mode 7 S+',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.MasterMode7]: 'Master Mode 7',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Revenant1]: 'Revenant T1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Revenant2]: 'Revenant T2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Revenant3]: 'Revenant T3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Revenant4]: 'Revenant T4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Revenant5]: 'Revenant T5',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Tarantula1]: 'Tarantula T1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Tarantula2]: 'Tarantula T2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Tarantula3]: 'Tarantula T3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Tarantula4]: 'Tarantula T4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Tarantula5]: 'Tarantula T5',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Sven1]: 'Sven T1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Sven2]: 'Sven T2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Sven3]: 'Sven T3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Sven4]: 'Sven T4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom1]: 'Voidgloom T1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom2]: 'Voidgloom T2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom3Sepulture]: 'Voidgloom T3 (Sepulture)',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom3Bruiser]: 'Voidgloom T3 (Bruiser)',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom3]: 'Voidgloom T3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom4Sepulture]: 'Voidgloom T4 (Sepulture)',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom4Bruiser]: 'Voidgloom T4 (Bruiser)',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Voidgloom4]: 'Voidgloom T4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Inferno1]: 'Inferno T1',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Inferno2]: 'Inferno T2',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Inferno3]: 'Inferno T3',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.Inferno4]: 'Inferno T4',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.KuudraBasic]: 'Kuudra Basic',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.KuudraHot]: 'Kuudra Hot',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.KuudraBurning]: 'Kuudra Burning',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.KuudraFiery]: 'Kuudra Fiery',
  [CarryDifficultyCreationModel.IngameCarryTypeEnum.KuudraInfernal]: 'Kuudra Infernal',
};

/**
 * Get the display label for an ingame carry type.
 */
export function getIngameCarryTypeLabel(ingameCarryType: CarryDifficultyCreationModel.IngameCarryTypeEnum | undefined | null): string {
  if (!ingameCarryType) return 'None';
  return INGAME_CARRY_TYPE_LABELS[ingameCarryType] || ingameCarryType;
}
